// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/shared"
	"net/http"
)

type GetTemplateDetailRequest struct {
	// Template entity ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetTemplateDetailRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetTemplateDetailResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	EmailTemplateResponse *shared.EmailTemplateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetTemplateDetailResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTemplateDetailResponse) GetEmailTemplateResponse() *shared.EmailTemplateResponse {
	if o == nil {
		return nil
	}
	return o.EmailTemplateResponse
}

func (o *GetTemplateDetailResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTemplateDetailResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
