// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/shared"
	"net/http"
)

type ReplaceVariablesAsyncRequestBody struct {
	EmailTemplateID *string `json:"email_template_id,omitempty"`
	// If true then skip document generation. This is useful when you want to replace html variables only. Speeds up the process.
	//
	SkipDocumentGeneration *bool                      `default:"false" json:"skip_document_generation"`
	VariableParameters     *shared.VariableParameters `json:"variable_parameters,omitempty"`
}

func (r ReplaceVariablesAsyncRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReplaceVariablesAsyncRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReplaceVariablesAsyncRequestBody) GetEmailTemplateID() *string {
	if o == nil {
		return nil
	}
	return o.EmailTemplateID
}

func (o *ReplaceVariablesAsyncRequestBody) GetSkipDocumentGeneration() *bool {
	if o == nil {
		return nil
	}
	return o.SkipDocumentGeneration
}

func (o *ReplaceVariablesAsyncRequestBody) GetVariableParameters() *shared.VariableParameters {
	if o == nil {
		return nil
	}
	return o.VariableParameters
}

type ReplaceVariablesAsyncRequest struct {
	RequestBody *ReplaceVariablesAsyncRequestBody `request:"mediaType=application/json"`
	// Job ID for tracking the status of document generation action
	JobID *string `queryParam:"style=form,explode=true,name=job_id"`
}

func (o *ReplaceVariablesAsyncRequest) GetRequestBody() *ReplaceVariablesAsyncRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *ReplaceVariablesAsyncRequest) GetJobID() *string {
	if o == nil {
		return nil
	}
	return o.JobID
}

type ReplaceVariablesAsyncResponse struct {
	// Success
	AsyncEmailTemplateResponse *shared.AsyncEmailTemplateResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReplaceVariablesAsyncResponse) GetAsyncEmailTemplateResponse() *shared.AsyncEmailTemplateResponse {
	if o == nil {
		return nil
	}
	return o.AsyncEmailTemplateResponse
}

func (o *ReplaceVariablesAsyncResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReplaceVariablesAsyncResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReplaceVariablesAsyncResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
