// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/shared"
	"net/http"
)

type ReplaceVariablesRequestBody struct {
	EmailTemplateID string `json:"email_template_id"`
	// If true then skip document generation. This is useful when you want to replace html variables only. Speeds up the process.
	//
	SkipDocumentGeneration *bool                      `default:"false" json:"skip_document_generation"`
	VariableParameters     *shared.VariableParameters `json:"variable_parameters,omitempty"`
}

func (r ReplaceVariablesRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReplaceVariablesRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReplaceVariablesRequestBody) GetEmailTemplateID() string {
	if o == nil {
		return ""
	}
	return o.EmailTemplateID
}

func (o *ReplaceVariablesRequestBody) GetSkipDocumentGeneration() *bool {
	if o == nil {
		return nil
	}
	return o.SkipDocumentGeneration
}

func (o *ReplaceVariablesRequestBody) GetVariableParameters() *shared.VariableParameters {
	if o == nil {
		return nil
	}
	return o.VariableParameters
}

type ReplaceVariablesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	EmailTemplateResponse *shared.EmailTemplateResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReplaceVariablesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReplaceVariablesResponse) GetEmailTemplateResponse() *shared.EmailTemplateResponse {
	if o == nil {
		return nil
	}
	return o.EmailTemplateResponse
}

func (o *ReplaceVariablesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReplaceVariablesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
