// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/shared"
	"net/http"
)

type SaveTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	EmailTemplateEntity *shared.EmailTemplateEntity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SaveTemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SaveTemplateResponse) GetEmailTemplateEntity() *shared.EmailTemplateEntity {
	if o == nil {
		return nil
	}
	return o.EmailTemplateEntity
}

func (o *SaveTemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SaveTemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
