// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/shared"
	"net/http"
)

type UpdateTemplateDetailRequest struct {
	EmailTemplateRequest *shared.EmailTemplateRequest `request:"mediaType=application/json"`
	// Template entity ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateTemplateDetailRequest) GetEmailTemplateRequest() *shared.EmailTemplateRequest {
	if o == nil {
		return nil
	}
	return o.EmailTemplateRequest
}

func (o *UpdateTemplateDetailRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateTemplateDetailResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success
	EmailTemplateEntity *shared.EmailTemplateEntity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateTemplateDetailResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateTemplateDetailResponse) GetEmailTemplateEntity() *shared.EmailTemplateEntity {
	if o == nil {
		return nil
	}
	return o.EmailTemplateEntity
}

func (o *UpdateTemplateDetailResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateTemplateDetailResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
