// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EmailTemplateResponse struct {
	Entity    *EmailTemplateEntity `json:"entity,omitempty"`
	Relations interface{}          `json:"relations,omitempty"`
}

func (o *EmailTemplateResponse) GetEntity() *EmailTemplateEntity {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *EmailTemplateResponse) GetRelations() interface{} {
	if o == nil {
		return nil
	}
	return o.Relations
}
