// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	AsOrganization *string `security:"scheme,type=apiKey,subtype=header,name=x-ivy-org-id"`
	EpilotAuth     *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	EpilotOrg      *string `security:"scheme,type=apiKey,subtype=header,name=x-epilot-org-id"`
}

func (o *Security) GetAsOrganization() *string {
	if o == nil {
		return nil
	}
	return o.AsOrganization
}

func (o *Security) GetEpilotAuth() *string {
	if o == nil {
		return nil
	}
	return o.EpilotAuth
}

func (o *Security) GetEpilotOrg() *string {
	if o == nil {
		return nil
	}
	return o.EpilotOrg
}
