// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ApproveAction - Type of approval action for the bulk message request.
// * APPROVE_WITH_CONSENT: Approve the bulk message request and send emails to queued recipients with consent
// * APPROVE_ALL: Approve the bulk message request and send emails to all queued recipients, including those without consent
type ApproveAction string

const (
	ApproveActionApproveWithConsent ApproveAction = "APPROVE_WITH_CONSENT"
	ApproveActionApproveAll         ApproveAction = "APPROVE_ALL"
)

func (e ApproveAction) ToPointer() *ApproveAction {
	return &e
}
func (e *ApproveAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "APPROVE_WITH_CONSENT":
		fallthrough
	case "APPROVE_ALL":
		*e = ApproveAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ApproveAction: %v", v)
	}
}
