// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateSystemTemplatesReq struct {
	TemplateNames []string `json:"template_names"`
}

func (o *CreateSystemTemplatesReq) GetTemplateNames() []string {
	if o == nil {
		return []string{}
	}
	return o.TemplateNames
}
