// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/internal/utils"
)

type CustomVariables struct {
	// Value to be Replaced
	Value *string `json:"value,omitempty"`
	// Template Variable Name
	Variable *string `json:"variable,omitempty"`
}

func (c CustomVariables) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomVariables) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *CustomVariables) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *CustomVariables) GetVariable() *string {
	if o == nil {
		return nil
	}
	return o.Variable
}
