// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EmailTemplateResponse struct {
	Entity *EmailTemplateEntity `json:"entity,omitempty"`
}

func (o *EmailTemplateResponse) GetEntity() *EmailTemplateEntity {
	if o == nil {
		return nil
	}
	return o.Entity
}
