// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type From struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (o *From) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *From) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
