// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TemplateType string

const (
	TemplateTypeEmail    TemplateType = "email"
	TemplateTypeDocument TemplateType = "document"
)

func (e TemplateType) ToPointer() *TemplateType {
	return &e
}

func (e *TemplateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "email":
		fallthrough
	case "document":
		*e = TemplateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TemplateType: %v", v)
	}
}
