// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	speakeasy_boolplanmodifier "github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/planmodifiers/boolplanmodifier"
	speakeasy_listplanmodifier "github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/planmodifiers/listplanmodifier"
	speakeasy_numberplanmodifier "github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/planmodifiers/numberplanmodifier"
	speakeasy_stringplanmodifier "github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/planmodifiers/stringplanmodifier"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/pkg/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/pkg/models/shared"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/validators"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &EmailTemplateResource{}
var _ resource.ResourceWithImportState = &EmailTemplateResource{}

func NewEmailTemplateResource() resource.Resource {
	return &EmailTemplateResource{}
}

// EmailTemplateResource defines the resource implementation.
type EmailTemplateResource struct {
	client *sdk.SDK
}

// EmailTemplateResourceModel describes the resource data model.
type EmailTemplateResourceModel struct {
	CreatedAt      types.String   `tfsdk:"created_at"`
	Org            types.String   `tfsdk:"org"`
	Schema         types.String   `tfsdk:"schema"`
	Title          types.String   `tfsdk:"title"`
	UpdatedAt      types.String   `tfsdk:"updated_at"`
	Attachments    []types.String `tfsdk:"attachments"`
	Bcc            []types.String `tfsdk:"bcc"`
	Body           types.String   `tfsdk:"body"`
	BrandID        types.Number   `tfsdk:"brand_id"`
	Cc             []types.String `tfsdk:"cc"`
	CreatedBy      types.Number   `tfsdk:"created_by"`
	File           types.String   `tfsdk:"file"`
	From           types.String   `tfsdk:"from"`
	ID             types.String   `tfsdk:"id"`
	Name           types.String   `tfsdk:"name"`
	Relations      types.String   `tfsdk:"relations"`
	Subject        types.String   `tfsdk:"subject"`
	SystemTemplate types.Bool     `tfsdk:"system_template"`
	Tags           []types.String `tfsdk:"tags"`
	To             []types.String `tfsdk:"to"`
	UpdatedBy      types.Number   `tfsdk:"updated_by"`
}

func (r *EmailTemplateResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_email_template"
}

func (r *EmailTemplateResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "EmailTemplate Resource",

		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `Created date`,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
			},
			"org": schema.StringAttribute{
				Computed:    true,
				Description: `Ivy Organization ID the entity belongs to`,
			},
			"schema": schema.StringAttribute{
				Computed:    true,
				Description: `URL-friendly identifier for the entity schema`,
			},
			"title": schema.StringAttribute{
				Computed:    true,
				Description: `Entity title`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `Updated date`,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
			},
			"attachments": schema.ListAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_listplanmodifier.SuppressDiff(speakeasy_listplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				ElementType: types.StringType,
				Description: `Email template attachments. Requires replacement if changed. `,
				Validators: []validator.List{
					listvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
			},
			"bcc": schema.ListAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_listplanmodifier.SuppressDiff(speakeasy_listplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				ElementType: types.StringType,
				Description: `Bcc. Requires replacement if changed. `,
				Validators: []validator.List{
					listvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
			},
			"body": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				Description: `Body. Requires replacement if changed. `,
			},
			"brand_id": schema.NumberAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.Number{
					numberplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_numberplanmodifier.SuppressDiff(speakeasy_numberplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				Description: `Brand ID. Equal 0 if available for All brands. Requires replacement if changed. `,
			},
			"cc": schema.ListAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_listplanmodifier.SuppressDiff(speakeasy_listplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				ElementType: types.StringType,
				Description: `Cc. Requires replacement if changed. `,
				Validators: []validator.List{
					listvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
			},
			"created_by": schema.NumberAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.Number{
					numberplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_numberplanmodifier.SuppressDiff(speakeasy_numberplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				Description: `Created by. Requires replacement if changed. `,
			},
			"file": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				Description: `Parsed as JSON.`,
				Validators: []validator.String{
					validators.IsValidJSON(),
				},
			},
			"from": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				Description: `Parsed as JSON.`,
				Validators: []validator.String{
					validators.IsValidJSON(),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				Description: `Requires replacement if changed. `,
			},
			"name": schema.StringAttribute{
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Required:    true,
				Description: `name. Requires replacement if changed. `,
			},
			"relations": schema.StringAttribute{
				Computed:    true,
				Description: `Parsed as JSON.`,
				Validators: []validator.String{
					validators.IsValidJSON(),
				},
			},
			"subject": schema.StringAttribute{
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Required:    true,
				Description: `Subject. Requires replacement if changed. `,
			},
			"system_template": schema.BoolAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_boolplanmodifier.SuppressDiff(speakeasy_boolplanmodifier.ExplicitSuppress),
				},
				Optional: true,
				MarkdownDescription: `If template is created by system (Double Opt-in, CMD invitation,...) then true, and some attributes can not be edited such as Name, To,...` + "\n" +
					`Remember to add default content of template to [system-template.ts](https://gitlab.com/e-pilot/product/email-templates/svc-email-templates-api/-/blob/main/lambda/HandlerFunction/src/enum/system-template.ts) enum for revert to original feature` + "\n" +
					`` + "\n" +
					`Requires replacement if changed. `,
			},
			"tags": schema.ListAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_listplanmodifier.SuppressDiff(speakeasy_listplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				ElementType: types.StringType,
				Description: `Entity tags. Requires replacement if changed. `,
			},
			"to": schema.ListAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_listplanmodifier.SuppressDiff(speakeasy_listplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				ElementType: types.StringType,
				Description: `To. Requires replacement if changed. `,
				Validators: []validator.List{
					listvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
			},
			"updated_by": schema.NumberAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.Number{
					numberplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_numberplanmodifier.SuppressDiff(speakeasy_numberplanmodifier.ExplicitSuppress),
				},
				Optional:    true,
				Description: `Updated by. Requires replacement if changed. `,
			},
		},
	}
}

func (r *EmailTemplateResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *EmailTemplateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *EmailTemplateResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	var request *shared.EmailTemplateRequest
	id := new(string)
	if !data.ID.IsUnknown() && !data.ID.IsNull() {
		*id = data.ID.ValueString()
	} else {
		id = nil
	}
	var tags []string = nil
	for _, tagsItem := range data.Tags {
		tags = append(tags, tagsItem.ValueString())
	}
	var attachments []interface{} = nil
	for _, attachmentsItem := range data.Attachments {
		var attachmentsTmp interface{}
		_ = json.Unmarshal([]byte(attachmentsItem.ValueString()), &attachmentsTmp)
		attachments = append(attachments, attachmentsTmp)
	}
	var bcc []interface{} = nil
	for _, bccItem := range data.Bcc {
		var bccTmp interface{}
		_ = json.Unmarshal([]byte(bccItem.ValueString()), &bccTmp)
		bcc = append(bcc, bccTmp)
	}
	body := new(string)
	if !data.Body.IsUnknown() && !data.Body.IsNull() {
		*body = data.Body.ValueString()
	} else {
		body = nil
	}
	brandID := new(float64)
	if !data.BrandID.IsUnknown() && !data.BrandID.IsNull() {
		*brandID, _ = data.BrandID.ValueBigFloat().Float64()
	} else {
		brandID = nil
	}
	var cc []interface{} = nil
	for _, ccItem := range data.Cc {
		var ccTmp interface{}
		_ = json.Unmarshal([]byte(ccItem.ValueString()), &ccTmp)
		cc = append(cc, ccTmp)
	}
	createdBy := new(float64)
	if !data.CreatedBy.IsUnknown() && !data.CreatedBy.IsNull() {
		*createdBy, _ = data.CreatedBy.ValueBigFloat().Float64()
	} else {
		createdBy = nil
	}
	var file interface{}
	if !data.File.IsUnknown() && !data.File.IsNull() {
		_ = json.Unmarshal([]byte(data.File.ValueString()), &file)
	}
	var from interface{}
	if !data.From.IsUnknown() && !data.From.IsNull() {
		_ = json.Unmarshal([]byte(data.From.ValueString()), &from)
	}
	name := data.Name.ValueString()
	subject := data.Subject.ValueString()
	systemTemplate := new(bool)
	if !data.SystemTemplate.IsUnknown() && !data.SystemTemplate.IsNull() {
		*systemTemplate = data.SystemTemplate.ValueBool()
	} else {
		systemTemplate = nil
	}
	var to []interface{} = nil
	for _, toItem := range data.To {
		var toTmp interface{}
		_ = json.Unmarshal([]byte(toItem.ValueString()), &toTmp)
		to = append(to, toTmp)
	}
	updatedBy := new(float64)
	if !data.UpdatedBy.IsUnknown() && !data.UpdatedBy.IsNull() {
		*updatedBy, _ = data.UpdatedBy.ValueBigFloat().Float64()
	} else {
		updatedBy = nil
	}
	request = &shared.EmailTemplateRequest{
		ID:             id,
		Tags:           tags,
		Attachments:    attachments,
		Bcc:            bcc,
		Body:           body,
		BrandID:        brandID,
		Cc:             cc,
		CreatedBy:      createdBy,
		File:           file,
		From:           from,
		Name:           name,
		Subject:        subject,
		SystemTemplate: systemTemplate,
		To:             to,
		UpdatedBy:      updatedBy,
	}
	res, err := r.client.EmailTemplates.SaveTemplate(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.EmailTemplateEntity == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedEmailTemplateEntity(res.EmailTemplateEntity)
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *EmailTemplateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *EmailTemplateResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.GetTemplateDetailRequest{
		ID: id,
	}
	res, err := r.client.EmailTemplates.GetTemplateDetail(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.EmailTemplateResponse == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedEmailTemplateEntity(res.EmailTemplateResponse.Entity)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *EmailTemplateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *EmailTemplateResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; all attributes marked as RequiresReplace

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *EmailTemplateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *EmailTemplateResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; entity does not have a configured DELETE operation
}

func (r *EmailTemplateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
