// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/pkg/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &EmailTemplateDataSource{}
var _ datasource.DataSourceWithConfigure = &EmailTemplateDataSource{}

func NewEmailTemplateDataSource() datasource.DataSource {
	return &EmailTemplateDataSource{}
}

// EmailTemplateDataSource is the data source implementation.
type EmailTemplateDataSource struct {
	client *sdk.SDK
}

// EmailTemplateDataSourceModel describes the data model.
type EmailTemplateDataSourceModel struct {
	Attachments    []types.String `tfsdk:"attachments"`
	Bcc            []types.String `tfsdk:"bcc"`
	Body           types.String   `tfsdk:"body"`
	BrandID        types.Number   `tfsdk:"brand_id"`
	Cc             []types.String `tfsdk:"cc"`
	CreatedAt      types.String   `tfsdk:"created_at"`
	CreatedBy      types.Number   `tfsdk:"created_by"`
	File           types.String   `tfsdk:"file"`
	From           types.String   `tfsdk:"from"`
	ID             types.String   `tfsdk:"id"`
	Name           types.String   `tfsdk:"name"`
	Org            types.String   `tfsdk:"org"`
	Relations      types.String   `tfsdk:"relations"`
	Schema         types.String   `tfsdk:"schema"`
	Subject        types.String   `tfsdk:"subject"`
	SystemTemplate types.Bool     `tfsdk:"system_template"`
	Tags           []types.String `tfsdk:"tags"`
	Title          types.String   `tfsdk:"title"`
	To             []types.String `tfsdk:"to"`
	UpdatedAt      types.String   `tfsdk:"updated_at"`
	UpdatedBy      types.Number   `tfsdk:"updated_by"`
}

// Metadata returns the data source type name.
func (r *EmailTemplateDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_email_template"
}

// Schema defines the schema for the data source.
func (r *EmailTemplateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "EmailTemplate DataSource",

		Attributes: map[string]schema.Attribute{
			"attachments": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `Email template attachments`,
			},
			"bcc": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `Bcc`,
			},
			"body": schema.StringAttribute{
				Computed:    true,
				Description: `Body`,
			},
			"brand_id": schema.NumberAttribute{
				Computed:    true,
				Description: `Brand ID. Equal 0 if available for All brands`,
			},
			"cc": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `Cc`,
			},
			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: `Created date`,
			},
			"created_by": schema.NumberAttribute{
				Computed:    true,
				Description: `Created by`,
			},
			"file": schema.StringAttribute{
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"from": schema.StringAttribute{
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Template entity ID`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `name`,
			},
			"org": schema.StringAttribute{
				Computed:    true,
				Description: `Ivy Organization ID the entity belongs to`,
			},
			"relations": schema.StringAttribute{
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"schema": schema.StringAttribute{
				Computed:    true,
				Description: `URL-friendly identifier for the entity schema`,
			},
			"subject": schema.StringAttribute{
				Computed:    true,
				Description: `Subject`,
			},
			"system_template": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: `If template is created by system (Double Opt-in, CMD invitation,...) then true, and some attributes can not be edited such as Name, To,...` + "\n" +
					`Remember to add default content of template to system_template enum for revert to original feature` + "\n" +
					``,
			},
			"tags": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `Entity tags`,
			},
			"title": schema.StringAttribute{
				Computed:    true,
				Description: `Entity title`,
			},
			"to": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `To`,
			},
			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: `Updated date`,
			},
			"updated_by": schema.NumberAttribute{
				Computed:    true,
				Description: `Updated by`,
			},
		},
	}
}

func (r *EmailTemplateDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *EmailTemplateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *EmailTemplateDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.GetTemplateDetailRequest{
		ID: id,
	}
	res, err := r.client.EmailTemplates.GetTemplateDetail(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.EmailTemplateResponse == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedEmailTemplateEntity(res.EmailTemplateResponse.Entity)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
