// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/provider/typeconvert"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *EmailTemplateResourceModel) RefreshFromSharedEmailTemplateEntity(ctx context.Context, resp *shared.EmailTemplateEntity) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.ID = types.StringValue(resp.ID)
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		r.Org = types.StringValue(resp.Org)
		r.Purpose = make([]types.String, 0, len(resp.Purpose))
		for _, v := range resp.Purpose {
			r.Purpose = append(r.Purpose, types.StringValue(v))
		}
		r.Schema = types.StringValue(resp.Schema)
		r.Tags = make([]types.String, 0, len(resp.Tags))
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		r.Title = types.StringValue(resp.Title)
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
		if resp.Attachments != nil {
			r.Attachments = make([]jsontypes.Normalized, 0, len(resp.Attachments))
			for _, attachmentsItem := range resp.Attachments {
				var attachments jsontypes.Normalized

				attachmentsResult, _ := json.Marshal(attachmentsItem)
				attachments = jsontypes.NewNormalizedValue(string(attachmentsResult))

				r.Attachments = append(r.Attachments, attachments)
			}
		}
		r.Bcc = make([]jsontypes.Normalized, 0, len(resp.Bcc))
		for _, bccItem := range resp.Bcc {
			var bcc jsontypes.Normalized

			bccResult, _ := json.Marshal(bccItem)
			bcc = jsontypes.NewNormalizedValue(string(bccResult))

			r.Bcc = append(r.Bcc, bcc)
		}
		r.Body = types.StringPointerValue(resp.Body)
		r.BrandID = types.Float64PointerValue(resp.BrandID)
		r.Cc = make([]jsontypes.Normalized, 0, len(resp.Cc))
		for _, ccItem := range resp.Cc {
			var cc jsontypes.Normalized

			ccResult, _ := json.Marshal(ccItem)
			cc = jsontypes.NewNormalizedValue(string(ccResult))

			r.Cc = append(r.Cc, cc)
		}
		r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
		if resp.File == nil {
			r.File = jsontypes.NewNormalizedNull()
		} else {
			fileResult, _ := json.Marshal(resp.File)
			r.File = jsontypes.NewNormalizedValue(string(fileResult))
		}
		if resp.From == nil {
			r.From = jsontypes.NewNormalizedNull()
		} else {
			fromResult, _ := json.Marshal(resp.From)
			r.From = jsontypes.NewNormalizedValue(string(fromResult))
		}
		r.Name = types.StringValue(resp.Name)
		r.Subject = types.StringPointerValue(resp.Subject)
		r.SystemTemplate = types.BoolPointerValue(resp.SystemTemplate)
		r.To = make([]jsontypes.Normalized, 0, len(resp.To))
		for _, toItem := range resp.To {
			var to jsontypes.Normalized

			toResult, _ := json.Marshal(toItem)
			to = jsontypes.NewNormalizedValue(string(toResult))

			r.To = append(r.To, to)
		}
		r.UpdatedBy = types.StringPointerValue(resp.UpdatedBy)
	}

	return diags
}

func (r *EmailTemplateResourceModel) ToOperationsGetTemplateDetailRequest(ctx context.Context) (*operations.GetTemplateDetailRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetTemplateDetailRequest{
		ID: id,
	}

	return &out, diags
}

func (r *EmailTemplateResourceModel) ToOperationsUpdateTemplateDetailRequest(ctx context.Context) (*operations.UpdateTemplateDetailRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	emailTemplateRequest, emailTemplateRequestDiags := r.ToSharedEmailTemplateRequest(ctx)
	diags.Append(emailTemplateRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var id string
	id = r.ID.ValueString()

	out := operations.UpdateTemplateDetailRequest{
		EmailTemplateRequest: emailTemplateRequest,
		ID:                   id,
	}

	return &out, diags
}

func (r *EmailTemplateResourceModel) ToSharedEmailTemplateRequest(ctx context.Context) (*shared.EmailTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	manifest := make([]string, 0, len(r.Manifest))
	for _, manifestItem := range r.Manifest {
		manifest = append(manifest, manifestItem.ValueString())
	}
	purpose := make([]string, 0, len(r.Purpose))
	for _, purposeItem := range r.Purpose {
		purpose = append(purpose, purposeItem.ValueString())
	}
	tags := make([]string, 0, len(r.Tags))
	for _, tagsItem := range r.Tags {
		tags = append(tags, tagsItem.ValueString())
	}
	var attachments []interface{}
	if r.Attachments != nil {
		attachments = make([]interface{}, 0, len(r.Attachments))
		for _, attachmentsItem := range r.Attachments {
			var attachmentsTmp interface{}
			_ = json.Unmarshal([]byte(attachmentsItem.ValueString()), &attachmentsTmp)
			attachments = append(attachments, attachmentsTmp)
		}
	}
	bcc := make([]interface{}, 0, len(r.Bcc))
	for _, bccItem := range r.Bcc {
		var bccTmp interface{}
		_ = json.Unmarshal([]byte(bccItem.ValueString()), &bccTmp)
		bcc = append(bcc, bccTmp)
	}
	body := new(string)
	if !r.Body.IsUnknown() && !r.Body.IsNull() {
		*body = r.Body.ValueString()
	} else {
		body = nil
	}
	brandID := new(float64)
	if !r.BrandID.IsUnknown() && !r.BrandID.IsNull() {
		*brandID = r.BrandID.ValueFloat64()
	} else {
		brandID = nil
	}
	cc := make([]interface{}, 0, len(r.Cc))
	for _, ccItem := range r.Cc {
		var ccTmp interface{}
		_ = json.Unmarshal([]byte(ccItem.ValueString()), &ccTmp)
		cc = append(cc, ccTmp)
	}
	createdBy := new(string)
	if !r.CreatedBy.IsUnknown() && !r.CreatedBy.IsNull() {
		*createdBy = r.CreatedBy.ValueString()
	} else {
		createdBy = nil
	}
	var file interface{}
	if !r.File.IsUnknown() && !r.File.IsNull() {
		_ = json.Unmarshal([]byte(r.File.ValueString()), &file)
	}
	var from interface{}
	if !r.From.IsUnknown() && !r.From.IsNull() {
		_ = json.Unmarshal([]byte(r.From.ValueString()), &from)
	}
	var name string
	name = r.Name.ValueString()

	var subject string
	subject = r.Subject.ValueString()

	systemTemplate := new(bool)
	if !r.SystemTemplate.IsUnknown() && !r.SystemTemplate.IsNull() {
		*systemTemplate = r.SystemTemplate.ValueBool()
	} else {
		systemTemplate = nil
	}
	to := make([]interface{}, 0, len(r.To))
	for _, toItem := range r.To {
		var toTmp interface{}
		_ = json.Unmarshal([]byte(toItem.ValueString()), &toTmp)
		to = append(to, toTmp)
	}
	updatedBy := new(string)
	if !r.UpdatedBy.IsUnknown() && !r.UpdatedBy.IsNull() {
		*updatedBy = r.UpdatedBy.ValueString()
	} else {
		updatedBy = nil
	}
	out := shared.EmailTemplateRequest{
		ID:             id,
		Manifest:       manifest,
		Purpose:        purpose,
		Tags:           tags,
		Attachments:    attachments,
		Bcc:            bcc,
		Body:           body,
		BrandID:        brandID,
		Cc:             cc,
		CreatedBy:      createdBy,
		File:           file,
		From:           from,
		Name:           name,
		Subject:        subject,
		SystemTemplate: systemTemplate,
		To:             to,
		UpdatedBy:      updatedBy,
	}

	return &out, diags
}
