// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-emailtemplate/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
)

var _ provider.Provider = (*EpilotEmailtemplateProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*EpilotEmailtemplateProvider)(nil)

type EpilotEmailtemplateProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// EpilotEmailtemplateProviderModel describes the provider data model.
type EpilotEmailtemplateProviderModel struct {
	EpilotAuth types.String `tfsdk:"epilot_auth"`
	EpilotOrg  types.String `tfsdk:"epilot_org"`
	ServerURL  types.String `tfsdk:"server_url"`
}

func (p *EpilotEmailtemplateProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "epilot-emailtemplate"
	resp.Version = p.version
}

func (p *EpilotEmailtemplateProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"epilot_auth": schema.StringAttribute{
				MarkdownDescription: `Authorization header with epilot OAuth2 bearer token.`,
				Optional:            true,
				Sensitive:           true,
			},
			"epilot_org": schema.StringAttribute{
				MarkdownDescription: `Overrides the target organization to allow shared tenant access.`,
				Optional:            true,
				Sensitive:           true,
			},
			"server_url": schema.StringAttribute{
				Description: `Server URL (defaults to https://email-template.sls.epilot.io)`,
				Optional:    true,
			},
		},
		MarkdownDescription: `Email template API: Email template API service`,
	}
}

func (p *EpilotEmailtemplateProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data EpilotEmailtemplateProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serverUrl := data.ServerURL.ValueString()

	if serverUrl == "" {
		serverUrl = "https://email-template.sls.epilot.io"
	}

	security := shared.Security{}

	if !data.EpilotAuth.IsUnknown() {
		security.EpilotAuth = data.EpilotAuth.ValueStringPointer()
	}

	if !data.EpilotOrg.IsUnknown() {
		security.EpilotOrg = data.EpilotOrg.ValueStringPointer()
	}

	providerHTTPTransportOpts := ProviderHTTPTransportOpts{
		SetHeaders: make(map[string]string),
		Transport:  http.DefaultTransport,
	}

	httpClient := http.DefaultClient
	httpClient.Transport = NewProviderHTTPTransport(providerHTTPTransportOpts)

	opts := []sdk.SDKOption{
		sdk.WithServerURL(serverUrl),
		sdk.WithSecurity(security),
		sdk.WithClient(httpClient),
	}

	client := sdk.New(opts...)
	resp.DataSourceData = client
	resp.EphemeralResourceData = client
	resp.ResourceData = client
}

func (p *EpilotEmailtemplateProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewEmailTemplateResource,
	}
}

func (p *EpilotEmailtemplateProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewEmailTemplateDataSource,
	}
}

func (p *EpilotEmailtemplateProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &EpilotEmailtemplateProvider{
			version: version,
		}
	}
}
