// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type From struct {
	Email types.String `tfsdk:"email"`
	Name  types.String `tfsdk:"name"`
}
